POST localhost:8080/bookings
Content-Type: application/json

{
  "userId": 1,
  "eventId": 1,
  "seats": [
    {
      "seatId": 5
    }
  ]
}

### confirm booking
POST localhost:8080/bookings/confirm
Content-Type: application/json

{
  "bookingId": 401
}