quarkus.datasource.username=postgres
quarkus.datasource.password=password

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/mydb
quarkus.datasource.jdbc.max-size=16

quarkus.hibernate-orm.schema-management.strategy=update
