# Datasource

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/mydb
quarkus.datasource.jdbc.max-size=16

quarkus.hibernate-orm.schema-management.strategy=update

# AWS SQS (LocalStack)
quarkus.sqs.endpoint-override=http://localhost:4566
quarkus.sqs.aws.region=us-east-1
quarkus.sqs.aws.credentials.type=static
quarkus.sqs.aws.credentials.static-provider.access-key-id=test
quarkus.sqs.aws.credentials.static-provider.secret-access-key=test

# Producer queue URL (mesma regiao)
queue.check-booking-pending-state.url=http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/check-booking-pending-state

# Consumer (SmallRye SQS)
mp.messaging.incoming.check-booking.connector=smallrye-sqs
mp.messaging.incoming.check-booking.queue=check-booking-pending-state

# Jwt config
mp.jwt.verify.issuer=ticketmaster
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=rsaPrivateKey.pem

# Disable Dev Services for both datasource and SQS
quarkus.datasource.devservices.enabled=false
quarkus.sqs.devservices.enabled=false
